export const countries = [
  { code: "AF", nameEn: "Afghanistan" },
  { code: "AL", nameEn: "Albania" },
  { code: "DZ", nameEn: "Algeria" },
  { code: "AD", nameEn: "Andorra" },
  { code: "AO", nameEn: "Angola" },
  { code: "AG", nameEn: "Antigua and Barbuda" },
  { code: "AR", nameEn: "Argentina" },
  { code: "AM", nameEn: "Armenia" },
  { code: "AU", nameEn: "Australia" },
  { code: "AT", nameEn: "Austria" },
  { code: "AZ", nameEn: "Azerbaijan" },
  { code: "BS", nameEn: "Bahamas" },
  { code: "BH", nameEn: "Bahrain" },
  { code: "BD", nameEn: "Bangladesh" },
  { code: "BB", nameEn: "Barbados" },
  { code: "BY", nameEn: "Belarus" },
  { code: "BE", nameEn: "Belgium" },
  { code: "BZ", nameEn: "Belize" },
  { code: "BJ", nameEn: "Benin" },
  { code: "BT", nameEn: "Bhutan" },
  { code: "BO", nameEn: "Bolivia" },
  { code: "BA", nameEn: "Bosnia and Herzegovina" },
  { code: "BW", nameEn: "Botswana" },
  { code: "BR", nameEn: "Brazil" },
  { code: "BN", nameEn: "Brunei" },
  { code: "BG", nameEn: "Bulgaria" },
  { code: "BF", nameEn: "Burkina Faso" },
  { code: "BI", nameEn: "Burundi" },
  { code: "CV", nameEn: "Cabo Verde" },
  { code: "KH", nameEn: "Cambodia" },
  { code: "CM", nameEn: "Cameroon" },
  { code: "CA", nameEn: "Canada" },
  { code: "CF", nameEn: "Central African Republic" },
  { code: "TD", nameEn: "Chad" },
  { code: "CL", nameEn: "Chile" },
  { code: "CN", nameEn: "China" },
  { code: "CO", nameEn: "Colombia" },
  { code: "KM", nameEn: "Comoros" },
  { code: "CG", nameEn: "Congo" },
  { code: "CR", nameEn: "Costa Rica" },
  { code: "HR", nameEn: "Croatia" },
  { code: "CU", nameEn: "Cuba" },
  { code: "CY", nameEn: "Cyprus" },
  { code: "CZ", nameEn: "Czech Republic" },
  { code: "DK", nameEn: "Denmark" },
  { code: "DJ", nameEn: "Djibouti" },
  { code: "DM", nameEn: "Dominica" },
  { code: "DO", nameEn: "Dominican Republic" },
  { code: "EC", nameEn: "Ecuador" },
  { code: "EG", nameEn: "Egypt" },
  { code: "SV", nameEn: "El Salvador" },
  { code: "GQ", nameEn: "Equatorial Guinea" },
  { code: "ER", nameEn: "Eritrea" },
  { code: "EE", nameEn: "Estonia" },
  { code: "SZ", nameEn: "Eswatini" },
  { code: "ET", nameEn: "Ethiopia" },
  { code: "FJ", nameEn: "Fiji" },
  { code: "FI", nameEn: "Finland" },
  { code: "FR", nameEn: "France" },
  { code: "GA", nameEn: "Gabon" },
  { code: "GM", nameEn: "Gambia" },
  { code: "GE", nameEn: "Georgia" },
  { code: "DE", nameEn: "Germany" },
  { code: "GH", nameEn: "Ghana" },
  { code: "GR", nameEn: "Greece" },
  { code: "GD", nameEn: "Grenada" },
  { code: "GT", nameEn: "Guatemala" },
  { code: "GN", nameEn: "Guinea" },
  { code: "GW", nameEn: "Guinea-Bissau" },
  { code: "GY", nameEn: "Guyana" },
  { code: "HT", nameEn: "Haiti" },
  { code: "HN", nameEn: "Honduras" },
  { code: "HU", nameEn: "Hungary" },
  { code: "IS", nameEn: "Iceland" },
  { code: "IN", nameEn: "India" },
  { code: "ID", nameEn: "Indonesia" },
  { code: "IR", nameEn: "Iran" },
  { code: "IQ", nameEn: "Iraq" },
  { code: "IE", nameEn: "Ireland" },
  { code: "IL", nameEn: "Israel" },
  { code: "IT", nameEn: "Italy" },
  { code: "JM", nameEn: "Jamaica" },
  { code: "JP", nameEn: "Japan" },
  { code: "JO", nameEn: "Jordan" },
  { code: "KZ", nameEn: "Kazakhstan" },
  { code: "KE", nameEn: "Kenya" },
  { code: "KI", nameEn: "Kiribati" },
  { code: "XK", nameEn: "Kosovo" },
  { code: "KW", nameEn: "Kuwait" },
  { code: "KG", nameEn: "Kyrgyzstan" },
  { code: "LA", nameEn: "Laos" },
  { code: "LV", nameEn: "Latvia" },
  { code: "LB", nameEn: "Lebanon" },
  { code: "LS", nameEn: "Lesotho" },
  { code: "LR", nameEn: "Liberia" },
  { code: "LY", nameEn: "Libya" },
  { code: "LI", nameEn: "Liechtenstein" },
  { code: "LT", nameEn: "Lithuania" },
  { code: "LU", nameEn: "Luxembourg" },
  { code: "MG", nameEn: "Madagascar" },
  { code: "MW", nameEn: "Malawi" },
  { code: "MY", nameEn: "Malaysia" },
  { code: "MV", nameEn: "Maldives" },
  { code: "ML", nameEn: "Mali" },
  { code: "MT", nameEn: "Malta" },
  { code: "MH", nameEn: "Marshall Islands" },
  { code: "MR", nameEn: "Mauritania" },
  { code: "MU", nameEn: "Mauritius" },
  { code: "MX", nameEn: "Mexico" },
  { code: "FM", nameEn: "Micronesia" },
  { code: "MD", nameEn: "Moldova" },
  { code: "MC", nameEn: "Monaco" },
  { code: "MN", nameEn: "Mongolia" },
  { code: "ME", nameEn: "Montenegro" },
  { code: "MA", nameEn: "Morocco" },
  { code: "MZ", nameEn: "Mozambique" },
  { code: "MM", nameEn: "Myanmar" },
  { code: "NA", nameEn: "Namibia" },
  { code: "NR", nameEn: "Nauru" },
  { code: "NP", nameEn: "Nepal" },
  { code: "NL", nameEn: "Netherlands" },
  { code: "NZ", nameEn: "New Zealand" },
  { code: "NI", nameEn: "Nicaragua" },
  { code: "NE", nameEn: "Niger" },
  { code: "NG", nameEn: "Nigeria" },
  { code: "KP", nameEn: "North Korea" },
  { code: "MK", nameEn: "North Macedonia" },
  { code: "NO", nameEn: "Norway" },
  { code: "OM", nameEn: "Oman" },
  { code: "PK", nameEn: "Pakistan" },
  { code: "PW", nameEn: "Palau" },
  { code: "PS", nameEn: "Palestine" },
  { code: "PA", nameEn: "Panama" },
  { code: "PG", nameEn: "Papua New Guinea" },
  { code: "PY", nameEn: "Paraguay" },
  { code: "PE", nameEn: "Peru" },
  { code: "PH", nameEn: "Philippines" },
  { code: "PL", nameEn: "Poland" },
  { code: "PT", nameEn: "Portugal" },
  { code: "QA", nameEn: "Qatar" },
  { code: "RO", nameEn: "Romania" },
  { code: "RU", nameEn: "Russia" },
  { code: "RW", nameEn: "Rwanda" },
  { code: "KN", nameEn: "Saint Kitts and Nevis" },
  { code: "LC", nameEn: "Saint Lucia" },
  { code: "VC", nameEn: "Saint Vincent and the Grenadines" },
  { code: "WS", nameEn: "Samoa" },
  { code: "SM", nameEn: "San Marino" },
  { code: "ST", nameEn: "Sao Tome and Principe" },
  { code: "SA", nameEn: "Saudi Arabia" },
  { code: "SN", nameEn: "Senegal" },
  { code: "RS", nameEn: "Serbia" },
  { code: "SC", nameEn: "Seychelles" },
  { code: "SL", nameEn: "Sierra Leone" },
  { code: "SG", nameEn: "Singapore" },
  { code: "SK", nameEn: "Slovakia" },
  { code: "SI", nameEn: "Slovenia" },
  { code: "SB", nameEn: "Solomon Islands" },
  { code: "SO", nameEn: "Somalia" },
  { code: "ZA", nameEn: "South Africa" },
  { code: "KR", nameEn: "South Korea" },
  { code: "SS", nameEn: "South Sudan" },
  { code: "ES", nameEn: "Spain" },
  { code: "LK", nameEn: "Sri Lanka" },
  { code: "SD", nameEn: "Sudan" },
  { code: "SR", nameEn: "Suriname" },
  { code: "SE", nameEn: "Sweden" },
  { code: "CH", nameEn: "Switzerland" },
  { code: "SY", nameEn: "Syria" },
  { code: "TW", nameEn: "Taiwan" },
  { code: "TJ", nameEn: "Tajikistan" },
  { code: "TZ", nameEn: "Tanzania" },
  { code: "TH", nameEn: "Thailand" },
  { code: "TL", nameEn: "Timor-Leste" },
  { code: "TG", nameEn: "Togo" },
  { code: "TO", nameEn: "Tonga" },
  { code: "TT", nameEn: "Trinidad and Tobago" },
  { code: "TN", nameEn: "Tunisia" },
  { code: "TR", nameEn: "Turkey" },
  { code: "TM", nameEn: "Turkmenistan" },
  { code: "TV", nameEn: "Tuvalu" },
  { code: "UG", nameEn: "Uganda" },
  { code: "UA", nameEn: "Ukraine" },
  { code: "AE", nameEn: "United Arab Emirates" },
  { code: "GB", nameEn: "United Kingdom" },
  { code: "US", nameEn: "United States" },
  { code: "UY", nameEn: "Uruguay" },
  { code: "UZ", nameEn: "Uzbekistan" },
  { code: "VU", nameEn: "Vanuatu" },
  { code: "VA", nameEn: "Vatican City" },
  { code: "VE", nameEn: "Venezuela" },
  { code: "VN", nameEn: "Vietnam" },
  { code: "YE", nameEn: "Yemen" },
  { code: "ZM", nameEn: "Zambia" },
  { code: "ZW", nameEn: "Zimbabwe" }
];
